name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - beta
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Check formatting
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test --verbose
      - name: Build
        run: cargo build --verbose
      - name: Install dependencies
        run: npm clean-install
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
